### ISSUE TITLE
TestFlight beta

### ISSUE THREAD

**Issue by habi** [sobri909/ArcMini#118]
I'm looking to test Arc (and Arc Mini) for tracking my location, and have used several other apps in the past.
Would it be possible to provide a TestFlight build of the App to help the app without having it to build myself?

Background:
I'm contemplating switching from [WHIB](https://apps.apple.com/us/app/where-have-i-been/id641553983) which works nice, but introduced a subscription model recently.
I'm all for donations, but a subscription is not something I'd like to pay to *only* efficiently track my location.
I've quickly tested Arc a while ago and was not happy with it's battery usage.
I hope that ArcMini (which, as I understand *only* tracks my location and does not assess *what* I do) would be exactly what I need...

**Comment by sobri909** [comment]
Hi @habi!

There are private beta TestFlight builds for Arc Mini, but they are for the private beta team, for testing and assisting with development, not for end users. 

For Arc's battery usage, it is lower than competing apps. If you are seeing significant battery use, please submit a support request on the [support forum](https://support.bigpaua.com). 

I suggest you don't share your opinions on paying for software with me in future. Telling me that you won't pay the fair price for the ongoing service provided by my app is not a winning opener.

**Comment by habi** [comment]
> There are private beta TestFlight builds for Arc Mini, but they are for the private beta team, for testing and assisting with development, not for end users.

I asked for a TestFlight build because I'd be happy to help with testing and assisting with development.
This is exactly what I try to do with four other apps that I use the TestFlight build for (see https://github.com/bryceco/GoMap/issues/492, https://github.com/OpenLitterMap/react-native/issues/17, https://github.com/vector-im/element-ios/issues/3819 and https://github.com/commonmark/commonmark-spec/issues/670 for recent issues I submitted related to those apps).

I understand that this is you don't want to offer to a strange passer-by like me, but thought that asking can't hurt.
 
> I suggest you don't share your opinions on paying for software with me in future. Telling me that you won't pay the fair price for the ongoing service provided by my app is not a winning opener.

I'm sorry that I didn't make myself clear in the statement.
I was speaking of WHIB (of which I use the premium/paid version), and their recent switch to a subscription model.
The app does *much* less than Arc in a much less polished way and I think the price you ask for Arc is fair for all the niceties it offers.

I personally am looking for a minimal app that only tracks location without the cool 'intelligence' of Arc behind, and thought that Arc Mini might be exactly what I'm looking for.
And would also happily pay a subscription to it.

**Comment by sobri909** [comment]
Ah, apologies! I did misread you there on subscriptions. My bad.

For Arc Mini, unfortunately the project is stalled at the moment. I misjudged the rate of progress Apple would make with SwiftUI, so going all-in on pure SwiftUI for Arc Mini has resulted in a bunch of blocker issues with no known workarounds. So while Arc Mini in its current state does achieve some of its goals, it's very scruffy UI, and I won't be coming back to working on it until probably after I've shipped Arc v4 (which is a mix of SwiftUI and UIKit). 

The non-UI layers of Arc Mini though are essentially the same as across all three apps (Mini, v3, and v4). So that stuff is still seeing active development (albeit most of those commits going into the private v3 and v4 repos lately, but I do tend to push those changes to all three repos periodically, to keep all fo the apps in sync). 

For a stripped down app for just recording and basic editing, to be honest I'd probably fork the Arc Mini repo then throw out almost the entire SwiftUI layer then build a new UI in UIKit/SwiftUI mix. Working with the current SwiftUI code is a losing battle, due to nasty bugs and regressions in SwiftUI. Building further on it before Apple make significantly more progress on SwiftUI is a job only suitable for masochists and people with considerably more spare time than me! 😏
